### ISSUE TITLE
Translation - Spanish

### ISSUE THREAD

**Issue by reloxx13** [reloxx13/SonWEB#10]
Looking for help to translate in spanish.

Translate /lang/lang_es.ini

**Comment by ascillato** [comment]
Working.....

**Comment by ascillato** [comment]
Done. PR #19

Thanks for this nice software :+1:

**Comment by ascillato** [comment]
With the correction on #20 I think that the Spanish Translation is complete. If you want #10 can be closed.

**Comment by reloxx13** [comment]
Heya,

added JS translation and need a new bunch of translations :p

**Comment by ascillato** [comment]
working....

**Comment by ascillato** [comment]
Done. PR #26
