### ISSUE TITLE
Translation - France

### ISSUE THREAD

**Issue by reloxx13** [reloxx13/SonWEB#11]
Looking for help to translate in france.

Translate /lang/lang_fr.ini

**Comment by MimbaMonkeyHouse** [comment]
`BY = "par"
TEXT_LOADING = "Chargement..."
CURL_ERROR = "ERREUR CURL"
ERROR = "ERREUR"
VIEW_ON_GITHUB = "Voir sur GitHub"
PLEASE_SELECT = "Veuillez sélectionner"
CANCEL = "Annuler"
PAGE_RELOAD = "Recharger la page"
PLEASE_ENTER = "Veuillez entrer"


[LOGIN]
LOGIN_INCORRECT = "Données de connexion incorrectes!"
LOGIN_USERNAME_PLACEHOLDER = "Nom d'utilisateur"
LOGIN_PASSWORD_PLACEHOLDER = "Mot de passe"
BTN_LOGIN = "Connexion"
BTN_REGISTER = "S'enregistrer"


[PAGE_TITLES]
DEVICES = "Appareils"
UPLOAD_NEW_FIRMWARE = "Mettre à jour le firmware des appareils"
MANAGE_DEVICE = "Gerer les appareils"
DEVICE_CONFIG = "Configurer les appareils"
ADD_DEVICE = "Ajouter un appareil"
EDIT_DEVICE = "Editer un appareil"
SITE_CONFIG = "Configuration"
DEVICE_UPDATE = "Mettre à jour les appareils"
LOGIN = "Connexion"
SITE_SELFUPDATE = "Mettre à jour SonWeb"
START = "Démarrer"
DEVICES_AUTOSCAN = "Recherche automatique"


[NAVI]
STARTPAGE = "Démarrer"
STARTPAGE_TOOLTIP = "Page de démarrage"
DEVICES = "Appareils"
DEVICES_TOOLTIP = "Infos sur les appareils"
UPDATE = "Mettre a jour"
UPDATE_TOOLTIP = "Aller au gestionnaire d'appareils"
SETTINGS = "Parametres"
SETTINGS_TOOLTIP = "Parametres SonWEB"
SELFUPDATE = "Mettre à jour SonWeb"
SELFUPDATE_TOOLTIP = "Vérifier les mises à jours SonWeb"
LOGOUT = "Déconnexion"
LOGOUT_TOOLTIP = "Déconnexion"
DEVICE_LIST = "Lister"
DEVICES_AUTOSCAN = "Recherche automatique"


[USER_CONFIG]
ERROR_CANNOT_CREATE_FILE = "Erreur d'écriture du fichier => %s"
CONFIG_SERVER_IP_HELP = "Adresse IP du serveur SonWEB"
MSG_USER_CONFIG_SAVED = "Configurations enregistrées"
CONFIG_SERVER_IP = "Adresse IP du serveur de mises a jour"
CONFIG_REFRESHTIME = "Temps de rafraichissement"
CONFIG_REFRESHTIME_NONE = "Ne pas rafraichir"
CONFIG_REFRESHTIME_SECOND = "Seconde"
CONFIG_REFRESHTIME_SECONDS = "Secondes"
BTN_SAVE_USER_CONFIG = "Enregistrer"
CONFIG_USERNAME = "Nom d'utilisateur"
CONFIG_PASSWORD = "Mot de passe"
CONFIG_AUTOMATIC_LANG = "Langue du firmware pour la mise ajour automatique"
CONFIG_AUTOMATIC_LANGAUGE_CN = "CN"
CONFIG_AUTOMATIC_LANGAUGE_DE = "DE"
CONFIG_AUTOMATIC_LANGAUGE_DS18X20 = "DS18X20"
CONFIG_AUTOMATIC_LANGAUGE_EN = "EN"
CONFIG_AUTOMATIC_LANGAUGE_ES = "ES"
CONFIG_AUTOMATIC_LANGAUGE_FR = "FR"
CONFIG_AUTOMATIC_LANGAUGE_NL = "NL"
CONFIG_AUTOMATIC_LANGAUGE_IT = "IT"
CONFIG_AUTOMATIC_LANGAUGE_PL = "PL"
CONFIG_AUTOMATIC_LANGAUGE_RU = "RU"
CONFIG_NIGHTMODE = "Mode de nuit"
CONFIG_NIGHTMODE_DISABLE = "Désactiver"
CONFIG_NIGHTMODE_ALWAYS = "Toujours"
CONFIG_NIGHTMODE_AUTO = "Auto"
CONFIG_LOGIN = "Configuration de connexion"
CONFIG_LOGIN_ENABLE = "Activer la connexion"


[DEVICE_ACTIONS]
ERROR_CANNOT_READ_CSV_FILE = "Le fichier CSV ne peut etre lu => %s"
ERROR_CANNOT_CREATE_TMP_FILE = "Le fichier temporaire ne peut etre créer => %s"
ERROR_PLEASE_ENTER_DEVICE_IP = "Veuillez entrer une adresse IP valide"
MSG_DEVICE_DELETE_DONE = "Appareil effacé"
MSG_DEVICE_EDIT_DONE = "Appareil édité"
MSG_DEVICE_ADD_DONE = "Appareil ajouté"
MSG_DEVICE_FOUND = "Appareil trouvé"
MSG_DEVICE_NOT_FOUND = "Appareil introuvable"
LABEL_NAME = "Nom"
BTN_SEARCH_DEVICE = "Rechercher"
BTN_BACK = "Retour"
BTN_SAVE = "Enregistrer"
DEVICE_NAME_TOOLTIP = "Insérer le nom"
DEVICE_IP = "Adresse IP de l'appareil"
DEVICE_IP_HELP = "L'adresse IP de l'appareil a ajouter"
DEVICE_PASSWORD = "Mot de passe de l'appareil"
DEVICE_PASSWORD_HELP = "Si vous souahitez un mot de passe du site, entrezle ici.
                       Attention: le mot de passe non crypté est enregistré dans le fichier decives.csv!"
DEVICE_USERNAME = "Nom d'utilisateur de l'appareil"
DEVICE_USERNAME_HELP = "Nom d'utilisateur du site. admin par défaut"
DEVICE_POSITION = "Position"
DEVICE_POSITION_HELP = "Ordonner les appareils."


[DEVICE_CONFIG]
ERROR_NO_DEVICE_SELECTED = "Pas d'appareil sélectionné"
MSG_CONFIG_SAVED = "Configuration enregistré"
CONFIG_FRIENDLYNAME = "Nom simple"
CONFIG_FRIENDLYNAME_HELP = "Nom Alexa"
CONFIG_POWERONSTATE = "Etat a l'allumage"
CONFIG_POWERONSTATE_HELP = "Etat apres la perte de courant"
CONFIG_POWERONSTATE_OPTION_0 = "Eteindre les relais au démarrage"
CONFIG_POWERONSTATE_OPTION_1 = "Allumer les relais au démarrage"
CONFIG_POWERONSTATE_OPTION_2 = "Guarder l'état en mémoire a l'allumage"
CONFIG_POWERONSTATE_OPTION_3 = "Alterner l'état en mémoire a l'allumage"
CONFIG_POWERONSTATE_OPTION_4 = "Allumer les relais au démarrage et bloquer leur controle"
CONFIG_LEDSTATE = "Etat du voyant"
CONFIG_LEDSTATE_HELP = "Comportement du voyant"
CONFIG_LEDSTATE_OPTION_0 = "Arret"
CONFIG_LEDSTATE_OPTION_1 = "Indiquer l'état par allumage du voyant (inversé sur le Sonoff Touch)"
CONFIG_LEDSTATE_OPTION_2 = "Indique l'inscription MQTT par clignotement"
CONFIG_LEDSTATE_OPTION_3 = "Indiquer l'état et l'inscription MQTT par clignotement"
CONFIG_LEDSTATE_OPTION_4 = "Indiquer les publications MQTT par clignotement"
CONFIG_LEDSTATE_OPTION_5 = "Indiquer l'état et les publications MQTT par clignotement"
CONFIG_LEDSTATE_OPTION_6 = "Indiquer tous les messages MQTT par clignotement"
CONFIG_LEDSTATE_OPTION_7 = "Indiquer l'état et les messages par clignotement"
CONFIG_SLEEP = "Hibernation (0-250ms)"
CONFIG_SLEEP_HELP = "Configurer le temps d'hibernation de 1 a 250 ms pour activer la sauvegarde d'énergie"
CONFIG_WIFICONFIG = "Configuration WIFI"
CONFIG_WIFICONFIG_HELP = "Comportement WIFI a la perte du réseau"`

**Comment by MimbaMonkeyHouse** [comment]
I'll get cracking with the rest when I get a chance!

**Comment by MimbaMonkeyHouse** [comment]
Here it is:
BY = "par"
TEXT_LOADING = "Chargement..."
CURL_ERROR = "ERREUR CURL"
ERROR = "ERREUR"
VIEW_ON_GITHUB = "Voir sur GitHub"
PLEASE_SELECT = "Veuillez sélectionner"
CANCEL = "Annuler"
PAGE_RELOAD = "Recharger la page"
PLEASE_ENTER = "Veuillez entrer"


[LOGIN]
LOGIN_INCORRECT = "Données de connexion incorrectes!"
LOGIN_USERNAME_PLACEHOLDER = "Nom d'utilisateur"
LOGIN_PASSWORD_PLACEHOLDER = "Mot de passe"
BTN_LOGIN = "Connexion"
BTN_REGISTER = "S'enregistrer"


[PAGE_TITLES]
DEVICES = "Appareils"
UPLOAD_NEW_FIRMWARE = "Mettre à jour le firmware des appareils"
MANAGE_DEVICE = "Gerer les appareils"
DEVICE_CONFIG = "Configurer les appareils"
ADD_DEVICE = "Ajouter un appareil"
EDIT_DEVICE = "Editer un appareil"
SITE_CONFIG = "Configuration"
DEVICE_UPDATE = "Mettre à jour les appareils"
LOGIN = "Connexion"
SITE_SELFUPDATE = "Mettre à jour SonWeb"
START = "Démarrer"
DEVICES_AUTOSCAN = "Recherche automatique"


[NAVI]
STARTPAGE = "Démarrer"
STARTPAGE_TOOLTIP = "Page de démarrage"
DEVICES = "Appareils"
DEVICES_TOOLTIP = "Infos sur les appareils"
UPDATE = "Mettre a jour"
UPDATE_TOOLTIP = "Aller au gestionnaire d'appareils"
SETTINGS = "Parametres"
SETTINGS_TOOLTIP = "Parametres SonWEB"
SELFUPDATE = "Mettre à jour SonWeb"
SELFUPDATE_TOOLTIP = "Vérifier les mises à jours SonWeb"
LOGOUT = "Déconnexion"
LOGOUT_TOOLTIP = "Déconnexion"
DEVICE_LIST = "Lister"
DEVICES_AUTOSCAN = "Recherche automatique"


[USER_CONFIG]
ERROR_CANNOT_CREATE_FILE = "Erreur d'écriture du fichier => %s"
CONFIG_SERVER_IP_HELP = "Adresse IP du serveur SonWEB"
MSG_USER_CONFIG_SAVED = "Configurations enregistrées"
CONFIG_SERVER_IP = "Adresse IP du serveur de mises a jour"
CONFIG_REFRESHTIME = "Temps de rafraichissement"
CONFIG_REFRESHTIME_NONE = "Ne pas rafraichir"
CONFIG_REFRESHTIME_SECOND = "Seconde"
CONFIG_REFRESHTIME_SECONDS = "Secondes"
BTN_SAVE_USER_CONFIG = "Enregistrer"
CONFIG_USERNAME = "Nom d'utilisateur"
CONFIG_PASSWORD = "Mot de passe"
CONFIG_AUTOMATIC_LANG = "Langue du firmware pour la mise ajour automatique"
CONFIG_AUTOMATIC_LANGAUGE_CN = "CN"
CONFIG_AUTOMATIC_LANGAUGE_DE = "DE"
CONFIG_AUTOMATIC_LANGAUGE_DS18X20 = "DS18X20"
CONFIG_AUTOMATIC_LANGAUGE_EN = "EN"
CONFIG_AUTOMATIC_LANGAUGE_ES = "ES"
CONFIG_AUTOMATIC_LANGAUGE_FR = "FR"
CONFIG_AUTOMATIC_LANGAUGE_NL = "NL"
CONFIG_AUTOMATIC_LANGAUGE_IT = "IT"
CONFIG_AUTOMATIC_LANGAUGE_PL = "PL"
CONFIG_AUTOMATIC_LANGAUGE_RU = "RU"
CONFIG_NIGHTMODE = "Mode de nuit"
CONFIG_NIGHTMODE_DISABLE = "Désactiver"
CONFIG_NIGHTMODE_ALWAYS = "Toujours"
CONFIG_NIGHTMODE_AUTO = "Auto"
CONFIG_LOGIN = "Configuration de connexion"
CONFIG_LOGIN_ENABLE = "Activer la connexion"


[DEVICE_ACTIONS]
ERROR_CANNOT_READ_CSV_FILE = "Le fichier CSV ne peut etre lu => %s"
ERROR_CANNOT_CREATE_TMP_FILE = "Le fichier temporaire ne peut etre créer => %s"
ERROR_PLEASE_ENTER_DEVICE_IP = "Veuillez entrer une adresse IP valide"
MSG_DEVICE_DELETE_DONE = "Appareil effacé"
MSG_DEVICE_EDIT_DONE = "Appareil édité"
MSG_DEVICE_ADD_DONE = "Appareil ajouté"
MSG_DEVICE_FOUND = "Appareil trouvé"
MSG_DEVICE_NOT_FOUND = "Appareil introuvable"
LABEL_NAME = "Nom"
BTN_SEARCH_DEVICE = "Rechercher"
BTN_BACK = "Retour"
BTN_SAVE = "Enregistrer"
DEVICE_NAME_TOOLTIP = "Insérer le nom"
DEVICE_IP = "Adresse IP de l'appareil"
DEVICE_IP_HELP = "Adresse IP de l'appareil a ajouter"
DEVICE_PASSWORD = "Mot de passe de l'appareil"
DEVICE_PASSWORD_HELP = "Si vous souahitez un mot de passe pour le site, entrez le ici.
                       Attention: le mot de passe non crypté est enregistré dans le fichier decives.csv!"
DEVICE_USERNAME = "Nom d'utilisateur de l'appareil"
DEVICE_USERNAME_HELP = "Nom d'utilisateur du site. admin par défaut"
DEVICE_POSITION = "Position"
DEVICE_POSITION_HELP = "Ordonner les appareils."


[DEVICE_CONFIG]
ERROR_NO_DEVICE_SELECTED = "Pas d'appareil sélectionné"
MSG_CONFIG_SAVED = "Configuration enregistré"
CONFIG_FRIENDLYNAME = "Nom simple"
CONFIG_FRIENDLYNAME_HELP = "Nom Alexa"
CONFIG_POWERONSTATE = "Etat a l'allumage"
CONFIG_POWERONSTATE_HELP = "Etat apres la perte de courant"
CONFIG_POWERONSTATE_OPTION_0 = "Eteindre les relais au démarrage"
CONFIG_POWERONSTATE_OPTION_1 = "Allumer les relais au démarrage"
CONFIG_POWERONSTATE_OPTION_2 = "Guarder l'état en mémoire a l'allumage"
CONFIG_POWERONSTATE_OPTION_3 = "Alterner l'état en mémoire a l'allumage"
CONFIG_POWERONSTATE_OPTION_4 = "Allumer les relais au démarrage et bloquer leur controle"
CONFIG_LEDSTATE = "Etat du voyant"
CONFIG_LEDSTATE_HELP = "Comportement du voyant"
CONFIG_LEDSTATE_OPTION_0 = "Arret"
CONFIG_LEDSTATE_OPTION_1 = "Indiquer l'état par allumage du voyant (inversé sur le Sonoff Touch)"
CONFIG_LEDSTATE_OPTION_2 = "Indiquer l'inscription MQTT par clignotement"
CONFIG_LEDSTATE_OPTION_3 = "Indiquer l'état et l'inscription MQTT par clignotement"
CONFIG_LEDSTATE_OPTION_4 = "Indiquer les publications MQTT par clignotement"
CONFIG_LEDSTATE_OPTION_5 = "Indiquer l'état et les publications MQTT par clignotement"
CONFIG_LEDSTATE_OPTION_6 = "Indiquer tous les messages MQTT par clignotement"
CONFIG_LEDSTATE_OPTION_7 = "Indiquer l'état et les messages par clignotement"
CONFIG_SLEEP = "Hibernation (0-250ms)"
CONFIG_SLEEP_HELP = "Configurer le temps d'hibernation de 1 a 250 ms pour activer la sauvegarde d'énergie"
CONFIG_WIFICONFIG = "Configuration WIFI"
CONFIG_WIFICONFIG_HELP = "Comportement WIFI a la perte du réseau"
CONFIG_WIFICONFIG_OPTION_0 = "Redémarrage Wifi - Redémarrer avec un point d'acces différent"
CONFIG_WIFICONFIG_OPTION_1 = "Configuration intelligente Wifi - Outil de configuration"
CONFIG_WIFICONFIG_OPTION_2 = "Manager Wifi - Démarrer le manager avec adresse IP 192.168.4.1"
CONFIG_WIFICONFIG_OPTION_3 = "WPS Wifi - Démarrer la configuration WPS pendant une minute"
CONFIG_WIFICONFIG_OPTION_4 = "Essayer un autre réseau Wifi - Pas de redémarrage"
CONFIG_WIFICONFIG_OPTION_5 = "Réessayer le meme réseau Wifi - Pas de redémarrage"
BTN_SAVE_DEVICE_CONFIG = "Enregistrer"
TAB_HL_GENERAL = "Général"
TAB_HL_NETWORK = "Réseau"
CONFIG_HOSTNAME_HELP = "Nom d'hote"
CONFIG_HOSTNAME = "Nom d'hotee"
CONFIG_IPADDRESS_HELP = "Adresse IP"
CONFIG_IPADDRESS = "Adresse IP"
CONFIG_GATEWAY_HELP = "Addresse de la passerelle"
CONFIG_GATEWAY = "Passerelle"
CONFIG_SUBNETMASK_HELP = "Masque de sous-réseau"
CONFIG_SUBNETMASK = "Masque de sous-réseau"
CONFIG_DNSSERVER_HELP = "Addresse du serveur DNS"
CONFIG_DNSSERVER = "Serveur DNS"
CONFIG_MACADDRESS_HELP = "Adresse MAC de l'appareil"
CONFIG_MACADDRESS = "Adresse MAC"
CONFIG_NTPSERVER_HELP = "Adresse NTP1"
CONFIG_NTPSERVER = "Adresse NTP1"
ERROR_COULD_NOT_GET_DATA = "L'appareil ne répond pas. Veuillez réessayer.
                           Trop de requetes ou redémarrage de l'appareil"
CONFIG_SSID1_HELP = "SSID du point d'acces 1"
CONFIG_SSID1 = "SSID (AP1)"
CONFIG_SSID1PW_HELP = "Mot de passe Wifi du point d'acces 1"
CONFIG_SSID1PW = "Mot de passe Wifi (AP1)"
CONFIG_SSID2_HELP = "SSID du point d'acces 2"
CONFIG_SSID2 = "SSID (AP2)"
CONFIG_SSID2PW_HELP = "Mot de passe Wifi du point d'acces 2"
CONFIG_SSID2PW = "Mot de passe Wifi (AP2)"
CONFIG_USE_AP_HELP = "Point d'acces a connecter"
CONFIG_USE_AP = "Utiliser le point d'acces"
CONFIG_AP1 = "AP1"
CONFIG_AP2 = "AP2"
DEVICE = "Appareil"


[DEVICE_UPDATE]
UPLOAD_DESCRIPTION = "Veuillez choisir le firmware minimal ou complet.
					Le mode automatique va télécharger le dernier firmware du Github de Tasmota"
FORM_CHOOSE_MINIMAL_FIRMWARE = "Firmware minimal"
FORM_CHOOSE_FULL_FIRMWARE = "Firmware complet"
BTN_UPLOAD_AUTOMATIC = "Automatique"
BTN_UPLOAD_AUTOMATIC_HELP = "Télécharger et utiliser le dernier firmware du Github de Tasmota"
BTN_UPLOAD_NEXT = "Suivant"
UPDATE = "Mise a jour"
UPLOAD_FIRMWARE_MINIMAL_INVALID_FILES = "Firmware minimal invalide"
UPLOAD_FIRMWARE_MINIMAL_ERR_NO_FILE = "Erreur de chargement: Firmware minimal non installé"
UPLOAD_FIRMWARE_MINIMAL_ERR_FORM_SIZE = "Erreur de chargement: Taille du firmware minimal trop élevée"
UPLOAD_FIRMWARE_MINIMAL_UNKNOWN_ERROR = "Erreur de chargement: Erreur inconnue du firmware minimal"
UPLOAD_FIRMWARE_MINIMAL_TOO_BIG = "Firmware minimal trop large (max. %s)"
UPLOAD_FIRMWARE_MINIMAL_WRONG_FORMAT = "Mauvais format. Installez le fichier BIN du firmware minimal!  %s"
UPLOAD_FIRMWARE_MINIMAL_COULD_NOT_SAVE = "Impossible d'enregistrer le firmware minimal sur le serveur! FWPath => %s"
UPLOAD_FIRMWARE_MINIMAL_LABEL = "Firmware minimal"
UPLOAD_FIRMWARE_MINIMAL_SUCCESSFULLY = "Succes de la mise a jour!"
UPLOAD_FIRMWARE_MINIMAL_SKIP = "Sauter"

UPLOAD_FIRMWARE_FULL_INVALID_FILES = "Firmware complet invalide"
UPLOAD_FIRMWARE_FULL_ERR_NO_FILE = "Erreur de chargement: Firmware complet non installé"
UPLOAD_FIRMWARE_FULL_ERR_FORM_SIZE = "Erreur de chargement: Taille du firmware complet trop élevée"
UPLOAD_FIRMWARE_FULL_UNKNOWN_ERROR = "Erreur de chargement: Erreur inconnue du firmware complet"
UPLOAD_FIRMWARE_FULL_TOO_BIG = "Firmware complet trop large (max. %s)"
UPLOAD_FIRMWARE_FULL_WRONG_FORMAT = "Mauvais format. Installez le fichier BIN du firmware complet!  %s"
UPLOAD_FIRMWARE_FULL_COULD_NOT_SAVE = "Impossible d'enregistrer le firmware complet sur le serveur! FWPath => %s"
UPLOAD_FIRMWARE_FULL_LABEL = "Firmware complet"
UPLOAD_FIRMWARE_FULL_SUCCESSFULLY = "Succes de la mise a jour!"
AUTO_SUCCESSFULL_DOWNLOADED = "Firmware téléchargé de GitHUB!"
AUTO_ERROR_DOWNLOAD = "Impossible de télécharger le firmware de GitHUB!"
UPLOAD_PLEASE_UPLOAD_FIRMWARE = "Veuillez ajouter un firmware!"
AUTO_WARNING_CFG_HOLDER = "Attention: Si vous avez changé le CFG_HOLDER, il sera réinitialisé et les parametres seront perdus!"
CHOOSE_DEVICES_TO_UPDATE = "Choisir l'appareil a mettre a jour"
BTN_START_UPDATE = "Démarrer la mise a jour"
NO_DEVICES_SELECTED = "Pas d'appareil a mettre a jour sélectionné"
MSG_SET_AUTOMATIC_LANG_FIRST = "Avant d'utiliser la mise a jour automatique,
                               veuillez choisr un parametre de langue"
LANGUAGE = "Langue"
VERSION = "Version"
DATE = "Date"


[DEVICES]
TABLE_HEAD_ALL = "Tous"
TABLE_HEAD_POSITION = "Pos."
TABLE_HEAD_ID = "ID"
TABLE_HEAD_NAME = "Nom
TABLE_HEAD_IP = "IP"
TABLE_HEAD_STATE = "Etat"
TABLE_HEAD_RSSI = "RSSI"
TABLE_HEAD_VERSION = "Version"
TABLE_HEAD_RUNTIME = "Execution"
TABLE_HEAD_TEMP = "Temp."
TABLE_HEAD_HUMIDITY = "Humidité"
TABLE_HEAD_PRESSURE = "Pression"
TABLE_HEAD_IDX = "IDX"
TABLE_HEAD_NEW_DEVICE = "Ajouter appareil"
LINK_OPEN_DEVICE_WEBUI = "Ouvrir l'interface de l'appareil"
LINK_DEVICE_CONFIG = "Configuratiom"
LINK_DEVICE_EDIT = "Editer"
LINK_DEVICE_DELETE = "Supprimer"
LINK_DEVICE_RESTART = "Redémarrer l'appareil"
DELETE_DEVICE = "Supprimer l'appareil"
DELETE_DEVICE_CONFIRM_TITLE = "Confirmer?"
DELETE_DEVICE_CONFIRM_TEXT = "Confirmer la suppression \"%s\" ( %s ) ?"
ERROR = "Erreur"
SHOW_MORE = "Plus d'infos"
HOSTNAME = "Nom d'hote"
MAC = "Mac"
MQTT = "MQTT"
POWERONSTATE = "Etat a l'allumage"
LEDSTATE = "Etat du voyant"
SAVEDATA = "Enregistrer les données"
SLEEP = "Hibernation"
BOOTCOUNT = "Nombre de redémarrage"
SAVECOUNT = "Nombre d'enregistrements"
LOGSTATES = "Logs SRL|WEB|SYS"
WIFICONFIG = "Configuration Wifi"
VCC = "Vcc"


[SELFUPDATE]
NO_UPDATE_FOUND = "Pas de mise a jour disponible"
UPDATE_FOUND = "Nouvelle mise a jour disponible"
UNKNOWN = "Inconnu"
BTN_START_SELFUPDATE = "Démarrer SelfUpdate"
SELFUPDATE_WARNING = "Attention: Cette option est en cours de développemtn!
                     Si vous utilisez cette option, sauvegardez vos données (data/MyConfig.php et data/devices.csv)"
SUCCESS_DOWNLOADED_ZIP_UPDATE = "Fichier ZIP SonWEB téléchargé"
ERROR_COULD_NOT_DOWNLOAD_ZIP = "Téléchargement du fichier ZIP SonWEB impossible"
SUCCESS_FILE_EXTRACTED_TO = "Fichier ZIP %s extrait vers %s"
ERROR_FILE_EXTRACTED_TO = "Impossible d'extraire le fichier Zip %s vers %s"
ERROR_EMPTY_FIRST_DIR = "Erreur: pas de dossier parent dans le fichier ZIP"
FIRST_DIRECTORY = "Dossier parent %s trouvé"
CONTENT_COPY_DONE = "Installation de la mise a jour effectuée"
TEMP_DIR_DELETED = "Effacement du dossier temporaire"
COPY_DONE = "Mise a jour effectuée"
ERROR_COULD_NOT_DELETE_TEMP_DIR = "Erreur: le dossier temporaire n'a pas pu etre effacé"
ERROR_COULD_NOT_COPY_UPDATE = "Erreur: la mise a jour n'a pas pu etre installee"
ERROR_COULD_NOT_EXTRACT = "Erreur: l'extraction du fichier ZIP a échouée"
OLD_SHA_VERSION = "Old Commit Revision => %s"
NEW_SHA_VERSION = "New Commit Revision => %s"
ERROR_CURL = "Erreur Curl"
ERROR_CHECK_CONNECTION = "Vérifiez votre connexion Internet"


[STARTPAGE]
NO_DEVICES_FOUND = "Pas d'appareil trouvé.</br>
                   Veuillez ajouter des appareils sur la page dédiée."


[DEVICES_AUTOSCAN]
BTN_START_AUTOSCAN = "Démarrer le scan automatique"
FROM_IP = "A partir de l'IP"
FROM_IP_HELP = "IP de démarrage de scan automatique"
TO_IP = "Jusau'a l'IP"
TO_IP_HELP = "IP de fin de scan automatique"
MSG_DEVICES_FOUND_COUNT = "Appareils détectés"
MSG_DEVICES_ADD_DONE = "Appareils ajouté"
MSG_NO_DEVICES_FOUND = "Pas d'appareil détecté"
MSG_SCANNING = "Scan automatique en cours..."
DEVICE = "Appareil"
BTN_SAVE_ALL = "Tout enregistrer"
BTN_TEST = "Tester"


[API]
CURL_ERROR = "ERREUR CURL"
JSON_ERROR = "ERREUR JSON"
JSON_ERROR_CONTACT_DEV = "Veuillez copier le message d'erreur et l'ajouter en erreur sur Github.
                         Le firmware Tasmota donné une erreur JSON qui doit etre ajustée dans SonWEB."
JSON_ANSWER = "Message JSON"


[JAVASCRIPT]
NO_REFRESH = "Ne pas rafraichir"
BLOCK_CHECK_CONNECTION = "Vérifier"
BLOCK_CHECK_CONNECTION_START_CHECK_TRY = "Vérifier la connexion | TRY => "
BLOCK_CHECK_CONNECTION_CHECK_ERROR_MSG = "Erreur de connexion! | MSG => "
BLOCK_CHECK_CONNECTION_CHECK_NO_RESPONSE_MSG = "Erreur: L'appareil ne répond pas! | MSG => "
BLOCK_CHECK_CONNECTION_CHECK_OK_VERSION = "Connexion réussie! | Current Version => "

BLOCK_OTAURL = "OTAURL"
BLOCK_OTAURL_SET_URL_FWTYPE = "Définir OTA URL du Firmware => "
BLOCK_OTAURL_SET_URL_FWURL = "OTA Url => "
BLOCK_OTAURL_ERROR_MSG = "Impossible de définir OTA URL | MSG => "
BLOCK_OTAURL_SUCCESS_FWTYPE = "OTA URL définie pour le Firmware => "
BLOCK_OTAURL_CHECK_NO_RESPONSE_MSG = "Erreur: Pas de réponse de l'appareil! | MSG => "

BLOCK_UPDATE = "Mise a jour"
BLOCK_UPDATE_START = "Démarrer la mise a jour de l'appareil..."
BLOCK_UPDATE_ERROR_MSG = "La mise a jour n'a pas pu démarrer! | MSG => "
BLOCK_UPDATE_SUCCESS = "Démarrage de la mise ajour de l'appareil"
BLOCK_UPDATE_CHECK_NO_RESPONSE_MSG = "Erreur: Pas de réponse de l'appareil!"

BLOCK_GLOBAL = "GLOBAL"
BLOCK_GLOBAL_ID = "ID"
BLOCK_GLOBAL_STEP = "ETAPE"
BLOCK_GLOBAL_START = "Démarrer la mise a jour"
BLOCK_GLOBAL_START_STEP_1 = "Démarrer l'étape 1"
BLOCK_GLOBAL_START_STEP_2 = "Démarrer l'étape 2"

BLOCK_CHECK_UPDATE = "Vérifier la mise a jour"
BLOCK_CHECK_UPDATE_ERROR_X_MIN = "Erreur: Pas de réponse de l'appareil depuis 5 minutes!!!"
BLOCK_CHECK_UPDATE_WAIT_X_SECONDS = "Attente de la mise ajour | Secondes => "
BLOCK_CHECK_UPDATE_UPDATE_DONE = "Mise a jour terminée!"
BLOCK_CHECK_UPDATE_DONE = "Terminé"
BLOCK_CHECK_UPDATE_DONE_MESSAGE = "============= Mise a jour terminée! ============="
BLOCK_CHECK_UPDATE_STILL_UPDATING = "Mise a jour pas encore effectuée"

UPTIME_SHORT_DAY = "j"
UPTIME_SHORT_DAYS = "Jours"
UPTIME_SHORT_HOUR = "h"
UPTIME_SHORT_HOURS = "Heures"
UPTIME_SHORT_MIN = "min"
UPTIME_SHORT_MINS = "Minutes"
UPTIME_SHORT_SEC = "s"
UPTIME_SHORT_SECS = "Secondes"

**Comment by reloxx13** [comment]
Thank you very much!
