### ISSUE TITLE
Translation - Russian

### ISSUE THREAD

**Issue by reloxx13** [reloxx13/SonWEB#13]
Looking for help to translate in russian.

Translate /lang/lang_ru.ini

**Comment by malikzh** [comment]
Hi! I began to translate the file into Russian, I think I'll finish it by the end of the week. Truth in translation there are some things, the context of which I can not understand. But, I'll write about later.

**Comment by reloxx13** [comment]
heya,


thank you ! 👍 

i added some placeholder files and added the languages to the switch, maybe its better to you to see where the translation takes place.

if you merge, resolve the lang_ru.ini with your file.

**Comment by reloxx13** [comment]
thank you very much! i just merged it :) 👍

**Comment by reloxx13** [comment]
Heya,

added JS translations and need a bunch of new transations :)

**Comment by malikzh** [comment]
Hi! I'll translate it for the rest of the week. Translations in the same file?

**Comment by reloxx13** [comment]
yup, always in the /lang/lang_ru.ini 👍

**Comment by malikzh** [comment]
OK :) 👍

**Comment by salopette** [comment]
Hi, wenn noch Hilfe in De->Ru benötigt wird,bitte melden.
Gruß Andrej

**Comment by reloxx13** [comment]
@salopette yup, schau einfach mal in die lang_ru.ini.

Seit der Übersetzung gibts ne Menge neue Texte :)
