### ISSUE TITLE
Start Page can't translate the word START

### ISSUE THREAD

**Issue by ascillato** [reloxx13/SonWEB#20]
Hi,

I have tested the _Spanish Translation_ and found that the word **START** on the _Page Title_ and on the _Label at the top of the page_ remains as START no matter which language you set. For Spanish should be **Inicio**

![image](https://user-images.githubusercontent.com/35405447/35553109-42d550ce-0575-11e8-9915-c090f4677bec.png)

How can be changed?

**Comment by reloxx13** [comment]
Uhh thanks for the hint, ill add it to the translation :)
