### ISSUE TITLE
Eternal expectation of data, why?

### ISSUE THREAD

**Issue by stepanovalex** [reloxx13/SonWEB#21]
![2018-01-30_15-12-47](https://user-images.githubusercontent.com/5058057/35565900-6ffc0d8a-05d0-11e8-80c6-9ea6ea5f65f6.png)

In the web interface of the switch, the data is:
![2018-01-30_15-16-30](https://user-images.githubusercontent.com/5058057/35565947-a8b52760-05d0-11e8-895e-54bb2f1176d3.png)

**Comment by reloxx13** [comment]
could you give me the response from
http://10.40.20.50/cm?cmnd=Status%202

**Comment by stepanovalex** [comment]
> http://10.40.20.50/cm?cmnd=Status%202

{"WARNING":"Need user=<username>&password=<password>"}

All my devices have a username / password

> are all devices from you on 5.10.0c ?

yes

**Comment by reloxx13** [comment]
you need to add your username&password in the request

http://10.40.20.50/cm?user=admin&password=YOURPASSWORDHERE&cmnd=Status%202

did you add your password on the device add/edit forumular? i added support for this 1-2 days ago.

**Comment by stepanovalex** [comment]
my user is not "admin"

**Comment by reloxx13** [comment]
so change it to your username :p

**Comment by stepanovalex** [comment]
![2018-01-30_15-39-06](https://user-images.githubusercontent.com/5058057/35566802-bef734f2-05d3-11e8-873e-7cf6c642e821.png)

**Comment by reloxx13** [comment]
ill investigate this later, thank you.

**Comment by stepanovalex** [comment]
Thanks!

**Comment by reloxx13** [comment]
heya,

please update sonweb :)

before 5.10.0j the json answers were translated. i would suggest you to at least update to 5.10.0j.
Those json translations are messing up alot :p

br
nils

**Comment by stepanovalex** [comment]
Many THANKS!!!

![2018-01-31_12-01-46](https://user-images.githubusercontent.com/5058057/35614016-afdd47e4-067e-11e8-81ab-4d30499d191d.png)
