### ISSUE TITLE
Translate JS Outputs

### ISSUE THREAD

**Issue by ascillato** [reloxx13/SonWEB#22]
Hi,

There is any way of translating the information while Uploading firmware to any other language?

![image](https://user-images.githubusercontent.com/35405447/35575242-a9c5e844-05ba-11e8-857b-e733e8de62d5.png)

**Comment by reloxx13** [comment]
hey,

at the current state not, im still looking for a solution.

those are javascript outputs, so i need a way to parse the lang.ini file into something readable for javascript. i want avoid having 2 diffrent i18n files to translate for each language.

i got a few ideas already, but this will take some time. hopefully i get it at the weekend done :)
has high prio for me, atleast ill translate it in english as default.

**Comment by reloxx13** [comment]
Update Start
Check connection try 1
Connection OK, current Version
Set MINIMAL OTA URL on device.
Trigger Update on Device
Wait 60sec for device Update
Update done
Start Step 2
Check connection try 1
Connection Ok, current Version
Set NEW FIRMWARE OTA URL on device
Trigger device Update
Wait 60 sec. for device Update
Update done

If check connection fails, it will try 3 times to connect.
If update is not done after 60sec, the process will wait another 30sec (device is installing and restarting while updating, this takes some time).

**Comment by ascillato** [comment]
There is another Translation issue when a device is not connected

![image](https://user-images.githubusercontent.com/35405447/35583107-9a831cde-05cf-11e8-8e92-a78880280e58.png)

Is this is also on Javascript?

**Comment by reloxx13** [comment]
yup, its the same issue :S

**Comment by reloxx13** [comment]
here you go :p

did just translate/check devices and update process for now.

**Comment by ascillato** [comment]
Found a little issue when updating.

![image](https://user-images.githubusercontent.com/35405447/35603523-80d43a1e-061c-11e8-95e8-e93086a56b0d.png)
