### ISSUE TITLE
Device Update not working

### ISSUE THREAD

**Issue by kskenyon** [reloxx13/SonWEB#25]
Device update correctly moves the firmware.bin files to data/firmwares folder but the OTA update doesn't take.  Everything looks like it works but the firmware is not updated.  I can update with the tasmota web page directly.  The AP order button is also switched somehow during the update attempt so I have to wipe and reload tasmota to be able to reconnect.  

OTA update IP isn't quite right or I'm missing something in the setup.  No errors are being thrown to troubleshoot from.

**Comment by kskenyon** [comment]
Nope, my SonWEB is installed in a SonWEB sub-directory in the apache root directory because I have several other apps running on the same apache server.  I access each of them through a different subdirectory.  That also keeps my apache root directory going to a dead end which is good.  I’m the only one accessing my apache server.  I do use username/password authentication in my apps in case someone gets that far from outside my firewall.

10.0.1.77/SonWEB/data/firmwares/sonoff-full.bin works!  So it is something in the way the OTA URL is formed by SonWEB.  The data/firmwares subdirectory has to be relative to SonWEB not apache root.

I would think most people would be running several apps from one apache server each with its own sub-directory.  This is not an unusual setup.  I have about 8 different web apps that I use regularly on the same httpd.  They all work OK in their own sub-directory.

At least you have another lead.  Keep up the great work!

Kevin

**Comment by reloxx13** [comment]
Hey Kevin,

i added support for subdirectory now.

Please try it out.

> I do use username/password authentication in my apps in case someone gets that far from outside my firewall.
So the OTA URL (10.0.1.77/SonWEB/data/firmwares/sonoff-full.bin) requests a username/password, too?

i dont think that this will work.

it should be username:password@10.0.1.77/SonWEB/data/firmwares/sonoff-full.bin

BR 
Nils

**Comment by kskenyon** [comment]
Works like a charm.  You’re getting there!

Another suggestion, default the firmware selections to the previous selection which can be overridden.  I often update Tasmota .bin files to the same location so there is no need to select a file each time.

Kevin

**Comment by reloxx13** [comment]
Heya,

Great that it works :)

For the firmware pre-selection i have some troubles:
I cannot detect which firmware version was uploaded, if i add this, you need to remember yourself which firmware was the latest you updated.

**Comment by kskenyon** [comment]
It would always upload the same file names and location.  Atom builds the same files to the same folder regardless of the version.  Might not be that way with other IDE’s.  Could it be a SonWEB setting for a default file name and location in the computer file system?

Kevin

**Comment by reloxx13** [comment]
heya dude :D

a webserver doe not have permission to other folders than teh documentroot (you can allow other folders but the normal unexpierence user could not hanlde this).

i would suggest you to make a small script to copy and rename the bins.

this is what i am using:

```
set version=5.12.0a-mod-1.12.1

mkdir %version%

copy ..\.pioenvs\sonoff\firmware.bin %version%\EN-firmware-%version%.bin
copy ..\.pioenvs\sonoff-CN\firmware.bin %version%\CN-firmware-%version%.bin
copy ..\.pioenvs\sonoff-DE\firmware.bin %version%\DE-firmware-%version%.bin
copy ..\.pioenvs\sonoff-ds18x20\firmware.bin %version%\DS18X20-firmware-%version%.bin
copy ..\.pioenvs\sonoff-ES\firmware.bin %version%\ES-firmware-%version%.bin
copy ..\.pioenvs\sonoff-FR\firmware.bin %version%\FR-firmware-%version%.bin
copy ..\.pioenvs\sonoff-IT\firmware.bin %version%\IT-firmware-%version%.bin
copy ..\.pioenvs\sonoff-minimal\firmware.bin %version%\MINIMAL-firmware-%version%.bin
copy ..\.pioenvs\sonoff-NL\firmware.bin %version%\NL-firmware-%version%.bin
copy ..\.pioenvs\sonoff-PL\firmware.bin %version%\PL-firmware-%version%.bin
```



i just change the version number at the top and double click it.

Folder Structur:
-Sonoff-Tasmota
   --releases
   --release.bat

**Comment by kskenyon** [comment]
Thanks, for the simple solution.  My wife always says I over complicate things.

Kevin
