### ISSUE TITLE
Self Update Error Messages

### ISSUE THREAD

**Issue by ascillato** [reloxx13/SonWEB#28]
I like a lot this **Self Update** Feature. :+1: 

Found 2 scenarios that triggers some errors:

1- When there is _No Internet Connection_, the _Self Update Page_ shows the following error message:
![image](https://user-images.githubusercontent.com/35405447/35697408-e37b089e-0768-11e8-85c2-e69a8dba1d1c.png)
It is possible to change that message to be something like _No Internet Connection_ without the label _New Update Found_ ?

2- When the _Internet Connection_ is slow, the _Self Update Page_ shows the following error message:
![image](https://user-images.githubusercontent.com/35405447/35697556-4e8c38ec-0769-11e8-9536-7574c61be4eb.png)
After 30 seconds while downloading, it stops and shows that message.
Can be updated the 30 seconds to show a message like: _Taking too long_ and that it continues downloading?

Thanks!!!

**Comment by reloxx13** [comment]
heya,

you i can fetch the "no internet error". ill tell you if fixed it.

ill try to set a higher time out.

**Comment by reloxx13** [comment]
hey,

please update and try it out :)

**Comment by ascillato** [comment]
Works Great!!!! :+1:
