### ISSUE TITLE
Missing keys on translation files

### ISSUE THREAD

**Issue by ascillato** [reloxx13/SonWEB#33]
There are 2 missing keys about LOG IN on the translation files ES, FR, IT, NL, PL, RU

On spanish the keys were updated by PR #32

![image](https://user-images.githubusercontent.com/35405447/35767872-6b2ab108-08d2-11e8-9fd2-93e67ff37b79.png)

Another issue is that selecting IT language, it changes to FR.

**Comment by reloxx13** [comment]
Uppps :D

Thanks ill fix this in the evening. Im not at home now :/

**Comment by reloxx13** [comment]
fixed 👍
