### ISSUE TITLE
Add DHT11/SHT3X Sensor

### ISSUE THREAD

**Issue by kskenyon** [reloxx13/SonWEB#37]
{"StatusSNS":{"Time":"2018-02-07T20:16:19","DHT11":{"Temperature":78.8,"Humidity":27.0},"SHT3X":{"Temperature":74.8,"Humidity":18.9},"TempUnit":"F"}}

**Comment by reloxx13** [comment]
Heya,
thanks for the request :)

DHT11 should work already.

You can see his values on the startpage and on the device list.

note: startpage sensors could be bugged after adding bootrstap atm, will check it later.

**Comment by kskenyon** [comment]
I should have edited that. There is also a SHT3X running on that through i2C.

Kevin

Fatfingered from my iPhone

**Comment by reloxx13** [comment]
Hah did not see it :D

will add it asap 👍

**Comment by reloxx13** [comment]
if you has a suggestion for better displaying the sensor data just tell me :)

two sensors at same device are displayed like this atm:
60°F|70°F

**Comment by kskenyon** [comment]
{"StatusSNS":{"Time":"2018-02-10T22:46:34","BMP280":{"Temperature":80.9,"Pressure":984.4},

**Comment by reloxx13** [comment]
@kskenyon pls make a new issue nexttime, i almost did not find this after deleteing the notify email already :X

addind BMP280 now :)
