### ISSUE TITLE
Tasmota already has spanish firmware .bin to upload - please add it to SonWEB

### ISSUE THREAD

**Issue by quikote** [reloxx13/SonWEB#39]
Hi. Thanks for this awesome tool.

Tasmota already has published ES binaries to be downloaded/uploaded.
 
Could you please add the spanish language to the automated update?

Thnaks in advance.

**Comment by reloxx13** [comment]
yup, just a moment :)

but i recommend you to always build your own firmware and set up your wifi in the user_config.h

if the sonoff ever will reset it wont connect again to your wifi and if you put it behind a wallswitch or in a lamp you need to disassemble everything to press the GPIO0 button to start the wifi manager to connect it again. sure its no problem if you just got a few devices.

the default wifi handler from tasmota git is wps, but for me the wps did not work with my fritzbox when i tried it.

**Comment by quikote** [comment]
Ok. Thanks for the advice...
But I do not how to build the firmware from my own from the source.... I'm a simple newbie  ;-)
I'll try to search how-to....

**Comment by ascillato** [comment]
@quikote, there is an explanation on the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Prerequisite)

**Comment by reloxx13** [comment]
here are also some howtos: https://github.com/arendst/Sonoff-Tasmota/wiki/Tutorials

i recommend to use atom, its easier.

**Comment by quikote** [comment]
Thanks ascillato & reloxx13 !
