### ISSUE TITLE
Fehler nach Update

### ISSUE THREAD

**Issue by h3adbang3r** [reloxx13/SonWEB#40]
Hi, 
ich habe sonWeb auf meinem Raspberry 3 Sketch.

Bis zum letztem Update lief auch alles ohne Probleme wenn ich sonweb wie folgt aufrief:
http://Domain.des.Pi/sonweb
![1673](https://user-images.githubusercontent.com/15799077/36062603-1453932e-0e70-11e8-955c-d7d2ea136842.jpg)

Jetzt komme ich mit diesem Aufruf zum login, und danach auch zur Übersicht. Allerdings funktioniert kein Aufruf aus dem neuem Menü sondern es kommt immer zu den jeweiligen Fehlermeldungen:

`Not Found

The requested URL /sonweb/selfupdate was not found on this server.
Apache/2.4.25 (Raspbian) Server at !Domain! Port 80`

`Not Found

The requested URL /sonweb/devices was not found on this server.
Apache/2.4.25 (Raspbian) Server at !Domain! Port 80`

Wie kann ich Sonweb helfen wieder zu funktionieren? BTW: englisch ist nicht so meines, sorry ;)

**Comment by reloxx13** [comment]
Huhu,

probier mal bitte nochmal das SelfUpdte aufzurufen mit 
http://Domain.des.Pi/sonweb/index.php?page=selfupdate

Ausserdem: 

sudo a2enmod rewrite
und die vhosts Datei anpassen ( Standard ist 000-default.conf in /etc/apache2/sites-enabled/ )
Dieser Block muss mit rein innerhalb des VirtualHost Blocks, Pfad bitte deinem System anpassen.
```
        <Directory /var/www/sonweb/>   
                Options Indexes FollowSymLinks MultiViews   
                AllowOverride All
                Order allow,deny   
                allow from all   
        </Directory>   
```


Sollte dann UNGEFÄHR so aussehen, auf dem Raspberry etwas anders aber hauptsache der Diretory Block ist drin ihc hoffe du verstehst was ich meine:
```
<VirtualHost *:9999>   
        ServerName sonweb   
        ServerAdmin webmaster@localhost   
        DocumentRoot /var/www/sonweb/   
        <Directory /var/www/sonweb/>   
                Options Indexes FollowSymLinks MultiViews   
                AllowOverride All
                Order allow,deny   
                allow from all   
        </Directory>   
        ErrorLog /var/log/apache2/error.log   
        LogLevel warn   
        CustomLog /var/log/apache2/access.log combined   
        ServerSignature On   
</VirtualHost>   
```

**Comment by h3adbang3r** [comment]
Huhu,

super danke läuft. Einzig die login ruft nicht die login.php auf. Ändere ich die URL auf "***/sonweb/login.php" klappt alles wie erwartet.

**Comment by reloxx13** [comment]
Bitte PHP Cache deaktivieren :D

sudo chmod 777 /etc/php/7.0/mods-available && sudo rm /etc/php/7.0/mods-available/opcache.ini -f && sudo service apache2 reload

Hier findest du auch noch ne Menge Infos und Hilfestellungen: 
http://forum.creationx.de/forum/index.php?thread/297-sonweb/
