### ISSUE TITLE
Devices Page aligned to the left with few data

### ISSUE THREAD

**Issue by ascillato** [reloxx13/SonWEB#42]
Hi,

The _devices page_ is aligned to the left of the screen when it has few data, and I think that should be better if center aligned.

![image](https://user-images.githubusercontent.com/35405447/36094428-fd272144-0fcc-11e8-8cf9-5f06fea11a28.png)

When the data is expanded with the _show more_ checkbox, the left alignment is the best option I think.

Thanks a lot for this tool!

**Comment by reloxx13** [comment]
Heya,

please try a ctrl+r fo refreshing cache.

it should be align :)

**Comment by ascillato** [comment]
I'm using Chrome.

I clear cache, do refresh, and remains left.

Browse the code with F12 and found **div class="row justify-content-center"** so it should be centered, but remains left.

I tested on Internet Explorer and also is displaying all left like the previous attached image.

**Comment by reloxx13** [comment]
thank for feedback, ill check it after work 👍

**Comment by ascillato** [comment]
Works great!!!

Thanks! :+1:
