### ISSUE TITLE
status updates broken?

### ISSUE THREAD

**Issue by Dunkelschunkel** [reloxx13/SonWEB#46]
Thank you so much for all your work and effort. I just recently discovered your work. To make a great product even better I have a small issue.

![image](https://user-images.githubusercontent.com/24452544/36167533-8dedd02c-10f6-11e8-9809-c05498b1166c.png)

Sonoff 1 is offline which is correct. However, Sonoff 2 is online. SonWEB is not able to retrieve statusinformation from the devices still online. And everything slows down tremendously.

Changing the Position of devices has no effect. But everything resorts to normal once everything is turned back on.

Thank you

**Comment by reloxx13** [comment]
heya,

pls delete sonoff 1.

sonoff 2 still offline? check your connection (firewall, ip).

u sure its 179 ? fritzbox and many other default is 178 in 3rd block .


which firmware version is installed?

**Comment by Dunkelschunkel** [comment]
Hi there,

Network is fine. I changed the default IP range of my fritzbox.

Latest tasmotaodified is installed.

Also checked on another computer in different environment same thing
happened there.



reloxx13 <notifications@github.com> schrieb am Mi. 14. Feb. 2018 um 13:58:

**Comment by reloxx13** [comment]
Heya,

ich schreibe mal auf deutsch weiter :p


Auf was hast du die Refreshtime stehen?

Sonst noch IOBroker am laufen?

Und bitte aufjedenflal noch die Info welche Firmware du drauf hast. Vor 5.10.0j wars glaub ich wurden die JSON Strings übersetzt, da kann es mit nicht englischen Versionen leider zu Problemen kommen, da es dort dann z.b. Wlan und nicht Wifi heißt.

Wenn es ein Verbindungsproblem wäre, müsste der Schalter eigt, auch in rot sein. Es sieht aber danach aus, als können nur die Infos nicht ausgelesen werden.

Bitte stelle auch nochmal sicher, dass der WebLog auf mindestens INFO steht (Weboberfläche von Tasmota -> Logging Konfigurieren).

**Comment by Dunkelschunkel** [comment]
Danke, Englisch rostet immer ein klein wenig bei mir.

Setup läuft ohne irgendwelche Besonderheiten - kein ioBroker. Nur Hue
Emulation an Homematic Virtual Layer auf Raspberry. SonWEB lauft auf
Windows PC. Habe SonWEB xampp portable runtergeladen und das letzte Master
Release händisch in das entsprechende htdocs-Verzeichnis gelegt. Erst
danach klappte auch das "Selfupdate". Aktualisierungsintervall ist auf 2
Sekunden - das ist Standard?

Firmware der sonoff-Geräte ist auf 5.12.0a-mod-1.12.1. von deinem
Repository. Kein Kennwort gesetzt.

Schalten über den Schalter klappt dennoch - allerdings auch sehr verzögert
- 4 bis 5 Sekunden eventuell.

Der Jo



2018-02-14 20:06 GMT+01:00 reloxx13 <notifications@github.com>:

**Comment by reloxx13** [comment]
hier mal die abfragen umgebaut: https://www.dropbox.com/s/rnx62apss0a0vbt/SonWEB.zip?dl=0
wenn du kannst probier es mal.

checke ich sonst morgen abend ins git ein

**Comment by Dunkelschunkel** [comment]
Test ist positiv verlaufen.

Wenn ein Gerät offline ist bleibt die Seite responsiv und die restlichen
erreichbaren Module werden weiterhin aktualisiert. Anbei zwei Screenshots,
auch Mal mit getauschter Sortierung.


Der Jo

reloxx13 <notifications@github.com> schrieb am Mi. 14. Feb. 2018 um 23:45:

**Comment by reloxx13** [comment]
Schau mal bitte wie es sich auf der Startseite verhält.

Dort ist noch die alte Methodik eingebaut, aber ich habe beim Umbauen noch eine wichtige Änderung gefunden die fehlte, undzwar hatten sie die Ajax Calls gegenseitig blockiert wenn die Session aktiv war. Dies kann man aber ausschalten.

Folglich:
Ajax dauert länger weil Gerät nicht antwortet.
Andere Ajax warten auf das was länger dauert und timen dadurch aus.

Mit der Änderung warten die Ajax Calls nicht mehr.

Hab dies dann gleich auch für die Startseite gemacht, könnte ebenfalls schon die Lösung fürs Problem sein :D

**Comment by reloxx13** [comment]
#49 startseite werde ich demnach auch umbauen
