### ISSUE TITLE
Device Discovery

### ISSUE THREAD

**Issue by ascillato** [reloxx13/SonWEB#47]
Hi,

Can be added a **Device Discovery** button to search for Tasmota devices on the local network?

Could be a ping from (localIP) i.e. 192.168.1.x where x goes from 2 to 255 and if there is a ping response, try to retrieve status?

And if it is a Tasmota it can be saved as new device.

I think should be handy tool.

the idea came from [Tasmota#1913](https://github.com/arendst/Sonoff-Tasmota/issues/1913)

**Comment by reloxx13** [comment]
yup, got that on my todo list already 👍 

but atm im working on the status updates of all devices, cuz their appear timeouts with too many parallel ajax request. im changing it from 10ajax/10curls to 1ajax/10curls.

**Comment by reloxx13** [comment]
Their will be a user input for the ip range.

Im having this as draft:
http://forum.creationx.de/forum/index.php?thread/503-soncheck2-tasmota-ger%C3%A4te-ohne-webserver-finden-und-konfigurieren/
(sry its only in german, its a bash script for detecting and some managing)

this sends a /cm?cmnd=Power to each ip in the range to check if its a tasmota device

**Comment by Schnittcher** [comment]
Deutsch ist super. 👍

**Comment by reloxx13** [comment]
its done 👌
