### ISSUE TITLE
Start screen device status (On/Off) differs from Device List

### ISSUE THREAD

**Issue by arendst** [reloxx13/SonWEB#54]
While the Start screen shows all device Off:

![image](https://user-images.githubusercontent.com/11044339/36311798-b81ec148-132c-11e8-9692-f36af7884e57.png)

The Device List shows correct status:

![image](https://user-images.githubusercontent.com/11044339/36311826-d73128a0-132c-11e8-8116-6b52774422fe.png)

**Comment by reloxx13** [comment]
Heya,

thanks for feedback :)

I already changed the status request method for the device list in #49.
But while doing this, i found another thing which could fix the startpage without changing.

Seems not to work :D Ill change the start page method to after work 👍 

Its good to see someone with alot devices to fix things :D

**Comment by reloxx13** [comment]
i fucked it up :D

pls make a selfipdat eor git pull and check start page again.

forgot to take out a timeout of 500ms for testing the ajaxs XD

**Comment by arendst** [comment]
Congratulations. It's ok now. Great feature this selfupdate.
