### ISSUE TITLE
Error State, Sonoff device Fatal exception

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/SonWEB#56]
Unfortunately the state of this devices showed ERROR and after some time it looks oke with the info of the devices, but toggled into error after a few seconds....

The restart message from the sonoff console shows this message:
00:00:06 MQT: tele/sonoff-pow-1/INFO3 = {"RestartReason":"Fatal exception:9 flag:2 (EXCEPTION) epc1:0x40204eec epc2:0x00000000 epc3:0x00000000 excvaddr:0x000014e9 depc:0x00000000"}

**Comment by RaymondMouthaan** [comment]
To fix this issue, I changed on the Settings page the `Refreshtime` from 5 sec (default) to `60 Seconds`.

**Comment by reloxx13** [comment]
what happens if you call the http command directly?

http://192.168.2.201/cm?cmnd=status%200

try to spam it a lil bit to figure out how the device reacts.

even on 2 sec my devices are not crashing, but as faster you go as unstabe it gets. if the device does not responde cuz of too many request the error msg will be displayed.

the esp can handle only a handfull of request.

**Comment by RaymondMouthaan** [comment]
I did some testing these are my findings...

### Used Equipment
- Devices : Sonoff Basic, Sonoff Pow and Wemos D1 Mini v2.1.0
- Firmware : Sonoff-Tasmota 5.12.0b
- Tool : JMeter

### Test 1 - SLOW
Request STATUS 0 - Show all status information (http://192.168.2.201/cm?cmnd=status%200) gives after 1 or 2 times a non-responsive Sonoff Tasmota device.

### Test 2 - 60 req/min - STABLE
Separate requests for STATUS, STATUS 1, STATUS 2, STATUS 3, STATUS 4, STATUS 5, STATUS 6, STATUS 7, STATUS 10, STATUS 11 with a delay of 1000 ms between each request (thoughput **60 req/min**) seems stable and gives correct responses.

### Test 3 - 90 req/min - STABLE
Separate requests for STATUS, STATUS 1, STATUS 2, STATUS 3, STATUS 4, STATUS 5, STATUS 6, STATUS 7, STATUS 10, STATUS 11 with a delay of 667 ms seconds between each request (thoughput **90 req/min**) seems stable and gives correct responses.

### Test 3 - 120 req/min - STABLE
Separate requests for STATUS, STATUS 1, STATUS 2, STATUS 3, STATUS 4, STATUS 5, STATUS 6, STATUS 7, STATUS 10, STATUS 11 with a delay of 500 ms between each request (thoughput **90 req/min**) seems stable and gives correct responses.

### Test 4 - 150 req/min - STABLE
Separate requests for STATUS, STATUS 1, STATUS 2, STATUS 3, STATUS 4, STATUS 5, STATUS 6, STATUS 7, STATUS 10, STATUS 11 with a delay of 400 ms between each request (thoughput **150 req/min**) seems stable and gives correct responses.

### Test 5 - 180 req/min - STABLE
Separate requests for STATUS, STATUS 1, STATUS 2, STATUS 3, STATUS 4, STATUS 5, STATUS 6, STATUS 7, STATUS 10, STATUS 11 with a delay of 333 ms between each request (thoughput **180 req/min**) seems stable and gives correct responses.

### Test 6 - 210 req/min - STABLE
Separate requests for STATUS, STATUS 1, STATUS 2, STATUS 3, STATUS 4, STATUS 5, STATUS 6, STATUS 7, STATUS 10, STATUS 11 with a delay of 286 ms between each request (thoughput **210 req/min**) seems stable and gives correct responses.

### Test 7 - 300 req/min - STABLE
Separate requests for STATUS, STATUS 1, STATUS 2, STATUS 3, STATUS 4, STATUS 5, STATUS 6, STATUS 7, STATUS 10, STATUS 11 with a delay of 200 ms between each request (thoughput **300 req/min**) seems stable and gives correct responses.

### Test 8 - SLOW
Just to make sure, I run again the STATUS 0 test with 15 req/min, but it couldn't be reached because of the response time of the Sonoff. It could reach a throughput of 7 req/min. It did not crash the device but it was very slow on the web interface.

### Conclusion
Based on these tests I would suggest to use individual / seperate requests with a minimal delay between each request. Instead of requesting STATUS 0 to get all info at once. Or even better in a lazy loading way (request when needed).

**Comment by reloxx13** [comment]
Heya, 

bruuh thanks for that time you investigated :)

their must something be wrong with your firmware/config if status 0 per http is crashing.

i can spam status 0 per http so much i want, its not crashing.

this basically tells your tests too, every other status request is answering fast and stable

From https://github.com/SuperHouse/esp-open-rtos/wiki/Crash-Dumps, exception 9 is
    Attempt to read/write memory with an unaligned address (for example, trying to read/write a 32-bit word at an address that is not a multiple of 4)


i think you have to open a ticket for theo the tasmota git :S

give it a try and disable mqtt on one device and spam it again (ctrl+r in browser is enough).

**Comment by reloxx13** [comment]
if u ike, you could also try the mod tasmota version from me.

check point 1 from here:
https://github.com/reloxx13/Sonoff-Tasmota-Modified/issues/1

i dont understand exactly what it does, @ascillato could this fix the status 0 crash if mqtt is enabled?

**Comment by RaymondMouthaan** [comment]
As we speak a test is running on status 0 with MQTT disabled, so far it looks good.

**Comment by ascillato** [comment]
Hi,

I tested on my devices and they don't crash.

The firmware you are using was compiled by you? if yes, please check if your compiling options are like this:

![image](https://user-images.githubusercontent.com/35405447/36329416-a47db992-1344-11e8-9de4-f6a57cfffbd8.png)

Because there is a problem with the new ESP8266 libraries. Tasmota works with IwIP v1.4

As explained on https://github.com/arendst/Sonoff-Tasmota/issues/1918

> Kind of known problem with 2.4.0 library ([esp8266/Arduino#4105](https://github.com/esp8266/Arduino/pull/4105))
> If compiled on Arduino IDE check your LwIP settings as documented in the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki).
> As last resort use 2.3.0 library.

Please, rebuild your firmware or try the prebuilt ones. ([Tasmota](https://github.com/arendst/Sonoff-Tasmota/releases)) or ([Tasmota Mod](https://github.com/reloxx13/Sonoff-Tasmota-Modified/releases))

**Comment by reloxx13** [comment]
thanks @ascillato for that informations 👍 

did not know it.

**Comment by ascillato** [comment]
Hope this solve @RaymondMouthaan problem

**Comment by RaymondMouthaan** [comment]
I disabled MQTT on the sonoff and ran a test for about 40 minutes on STATUS 0 with a load of 2.0 requests per second, with out any errors. 

Also SonWeb runs fine now for this device.

Regarding my firmware - yes, i build it myself using platform.io in Atom. I have no idea how or where to set the settings you mentioned above @ascillato in platform.io Is there a way if these settings / libraries are the correct ones?

Meanwhile i will try the re-build version and do another test :-)

Thanks for all the help so far 👍

**Comment by arendst** [comment]
Pio uses 1.4 prebuilt. It's in a build script somewhere in your windows user/loginname/.pio folder so that's ok.

**Comment by ascillato** [comment]
Ok, for platform.io the configuration is as the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/PlatformIO)

Another test you can do (to see if this is a library problem) is uploading a [precompiled version](https://github.com/arendst/Sonoff-Tasmota/releases/download/v5.12.0/sonoff.bin) and run your tests.

**Comment by reloxx13** [comment]
i use atom too, but i dont have a mqtt server for now.

but i can enabled mqtt and spammed status 0 without problems, too.


be sure you opened the project by the platformio.ini file (import arduino project) and did not create a new project by existing files (open project) on the PlatformIO Home Page (top menu->platformio->home).

**Comment by ascillato** [comment]
@RaymondMouthaan the prebuild version works for you?

**Comment by RaymondMouthaan** [comment]
It took a while to get my Pow flashed hahaha .. but i am running a test now (2 requests/sec) on STATUS 0 with pre-compiled version of Theo and it seems alright with MQTT enabled....

**Comment by ascillato** [comment]
nice :+1:

**Comment by RaymondMouthaan** [comment]
Now flashing it back to my own build version (with pio) ..

**Comment by RaymondMouthaan** [comment]
I tried different names for the mqtt topic 

- sonoff-pow-1 : failed
- sonoff_pow_1 : failed
- sonoffpow1 : failed
- sonoffpow : failed
- sonoff : passed 👍 

Confused ..

**Comment by ascillato** [comment]
wow, strange.

and those names with the prebuild firmware also fail?

**Comment by RaymondMouthaan** [comment]
With pre-build and topic name sonoff-pow-3 it fails ...

**Comment by ascillato** [comment]
I run some tests with _sonoff-pow-3_ and could not make it fail. Sorry. I check and recheck the data you post and could not find any clue.

I think that you should open a **new issue** under https://github.com/arendst/Sonoff-Tasmota because it seems to be a Firmware or device problem, and a lot of experienced people are there.

I will also follow your issue there because I want to know the fix for it.

**Comment by RaymondMouthaan** [comment]
I will do that ... thanks so far for your help !

I am just wondering, could it be related to the mqtt broker? Which one do you use? 
I use emqtt (with in a docker container).

**Comment by ascillato** [comment]
I use the one embedded on Home Assistant (HBMQTT broker).

**Comment by RaymondMouthaan** [comment]
I am still stuck on this issue, which makes SonWeb unfortunately unusable for me :( 

I am not sure whether it is related to the topic names or the firmware or my mqtt broker (emqtt) or my network setup or maybe even my docker swarm. 

Anyways ... i'll open a new issue at https://github.com/arendst/Sonoff-Tasmota and do some more investigation and tests to hopefully tackle this issue. Hopefully you guys consider my proposal in the conclusion section of my previous comment.

**Comment by RaymondMouthaan** [comment]
The story continues here [1968](https://github.com/arendst/Sonoff-Tasmota/issues/1968)
