### ISSUE TITLE
[Question] Docker Persistent Directories

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/SonWEB#57]
Hi,

Which directories / files should be kept saved after reinstall / version update etcetera ?

I am working on a docker image for SonWeb, so that SonWeb can run within a docker container. But I like to store its data out side the container., so that configured devices can be restored after redeployment / restart of the container. 

This directory /var/www/sonweb/data seems important for persistent, is there any other which I might have overlooked?

**Comment by reloxx13** [comment]
yup, just the data folder, data/MyConfig.php and data/devices.csv

**Comment by RaymondMouthaan** [comment]
Great 👍🏼

It’s working 🎉
