### ISSUE TITLE
Button Size of start autoscan (on spanish translation)

### ISSUE THREAD

**Issue by ascillato** [reloxx13/SonWEB#60]
Hi @reloxx13,

Found that the size of the _Start AutoScan_ button is changing its size depending on the width of the screen, but the text inside some times get cut.

**Full Screen: (button text cutted)**
![image](https://user-images.githubusercontent.com/35405447/36391283-ab931672-1584-11e8-9c1e-eee0cd46c81e.png)

**Small Screen: (button text OK)**
![image](https://user-images.githubusercontent.com/35405447/36391303-baa2b118-1584-11e8-8148-becb71f74c48.png)

**Medium Screen: (button text cutted)**
![image](https://user-images.githubusercontent.com/35405447/36391411-2350e2b6-1585-11e8-99b6-1e31f9b52b66.png)

I tested that eliminating the `<div class="col-sm-4">` the button width is shown as the width of the previous labels and the button text is not cutted.

Are you Ok with this change?

**Comment by reloxx13** [comment]
sure 👍

**Comment by reloxx13** [comment]
col-12 col-xs-6 will also do, but you can just push your changes ill check or adjust the button then.

**Comment by ascillato** [comment]
Yes, you are right! I put col-12 and col-sm-12 and now everything can be read on the button.

Thanks!

Really like SonWEB. Using it a lot :+1:
