### ISSUE TITLE
OTA Server IP field not translated

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/SonWEB#63]
On both Settings Page and Update Page the OTA Server IP field is not translated.

![screen shot 2018-02-19 at 19 36 31](https://user-images.githubusercontent.com/25717738/36392800-2c179e94-15ad-11e8-9ad2-082d9ece779e.png)
![screen shot 2018-02-19 at 19 37 28](https://user-images.githubusercontent.com/25717738/36392801-2c2dffea-15ad-11e8-8edc-a52c69481597.png)

**Comment by ascillato** [comment]
Please add the key `DEFAULT_HOST_IP_PLACEHOLDER` under `[USER_CONFIG]`

`DEFAULT_HOST_IP_PLACEHOLDER = "Please enter a OTA Server IP!"`

**Comment by RaymondMouthaan** [comment]
Its there already . in the NL file

**Comment by ascillato** [comment]
you are right! it is there. sorry.

I check on my pc and I see this.

![image](https://user-images.githubusercontent.com/35405447/36393503-a608bf72-158e-11e8-8f38-60997058d83e.png)

I update SonWEB few minutes ago with the selfupdate button. Try to update again to see if the problem solves.

**Comment by reloxx13** [comment]
heya,

its not translated in the NL language file :D

**Comment by RaymondMouthaan** [comment]
its about the default value in the field ;)

and this is in the dutch language file : DEFAULT_HOST_IP_PLACEHOLDER = "Voer een OTA Server IP in aub.!"

**Comment by reloxx13** [comment]
ahh its "correct" in someway.

if you dont have a MyConfig.php i write down a new file with default values.


ill remove it and just write "please enter" translated and keep an empty default value.

and add a help text under the input

**Comment by ascillato** [comment]
The hint on those fields is the `PLEASE_ENTER` key

**Comment by RaymondMouthaan** [comment]
I have a MyConfig.php contains the english text, thats why it gets filled by the english sentence and not the dutch .. I guess it works as designed 👍   

<?php return array (
  'ota_server_ip' => 'Please enter a OTA Server IP!',
  'username' => 'admin',
  'password' => '21232f297a57a5a743894a0e4a801fc3',
  'refreshtime' => 'none',
  'current_git_sha' => '03c25e098349370f12a1b2a3773ea614d0ce5950',
  'update_automatic_lang' => 'EN',
  'nightmode' => 'auto',
  'login' => '0',
) ; ?>

**Comment by reloxx13** [comment]
fixed 👍 

[USER_CONFIG]
CONFIG_SERVER_IP_HELP = "The IP from the SonWEB Server"
