### ISSUE TITLE
devices_autoscan

### ISSUE THREAD

**Issue by kskenyon** [reloxx13/SonWEB#64]
Autoscan doesn't work if SonWEB is not at the root directory of httpd.  

/var/www/html/"SonWEB subdirectory"

Kevin

**Comment by reloxx13** [comment]
heya,

did you get any error message?

it works for my in my ubuntu test vm in subdir :S

note: already added devices will not getting found again.

**Comment by kskenyon** [comment]
Oh, it only works for new devices?  I thought it would rediscover devices where the IP had changed.  (In other words, the MAC address hasn’t changed.)

I did get an error message in /var/log/httpd/error_log with Apache saying it couldn’t find the php file in the httpd root directory.  It isn’t there.

Kevin

**Comment by ascillato** [comment]
@kskenyon it is working now for you?

**Comment by kskenyon** [comment]
The error I saw looks like it is from a hacker scan not SonWEB autoscan.  My error.

**Comment by reloxx13** [comment]
what is a hacker scan =O

**Comment by kskenyon** [comment]
Someone is hitting my cgi-bin directory looking for common php files. It’s empty.  I have application based password protection. I access my web server from several different IP addresses.  I should probably change the port.  

I suppose I could try deleting cgi-bin in the www directory if it doesn’t cause an error.  Not a big deal.
