### ISSUE TITLE
Auto scan From IP and To IP are not saved

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/SonWEB#67]
On the auto scan page the From IP and To IP are filled with default values 192.168.178.1 and 192.168.178.254, after changing them to a different range eg. 192.168.2.1 ~ 192.168.2.254 and run the scan, these new range is not saved when switch pages. So for each auto scan a user must re-enter it's From IP and To IP.

**Comment by reloxx13** [comment]
yeah, i thought this would be nice to save x.x

otherwise, you should only use this once, when your devices are added you wont use it again. 
but its no big deal, i can add it to the MyConfig to save them :)

**Comment by reloxx13** [comment]
late but done :p
