### ISSUE TITLE
5.12.0c time display problem

### ISSUE THREAD

**Issue by kskenyon** [reloxx13/SonWEB#68]
Pos. | Name | IP | State |   | Version | Runtime | Temp. | Humidity | Pressure | Add device
1 | mini1 | 10.0.1.117 |   | 100% | 5.12.0c | NaNd NaNh NaNm NaNs | 69.2°F77.9°F | 38.7% | 997 hPa |

**Comment by reloxx13** [comment]
ill check it

**Comment by reloxx13** [comment]
heya,

please give me a status 0 response from your device,

its working for me:

![grafik](https://user-images.githubusercontent.com/14855001/36486667-4fa06134-171f-11e8-912d-c0c3b8ba5934.png)

try ctrl+r to clean cache or anothe browser to exclude cache as a problem.

if you use chrome, its very cache greedy as other browsers. i did almost everything in the code which i know to avoid cache problems, but chrome dont cares alot :D
by chrome clear cache over the settings.

**Comment by reloxx13** [comment]
http://10.0.1.117/cm?cmnd=status%200

**Comment by reloxx13** [comment]
which language version are you using?

**Comment by kskenyon** [comment]
EN

{
  "StatusPRM" : {
    "Baudrate" : 115200,
    "GroupTopic" : "sonoffs",
    “OtaUrl” : <snip>
    "Uptime" : "0T00:40:36",
    "StartupUTC" : "2018-02-21T14:17:18",
    "Sleep" : 0,
    "BootCount" : 80,
    "SaveCount" : 6723,
    "SaveAddress" : "F7000"
  }
}

I only have MQTT access right now since I’m not home.  It looks like Uptime is there.  Still there after browser refresh.  Using Safari.

K

**Comment by reloxx13** [comment]
kay got it, safari only bug :D

**Comment by reloxx13** [comment]
are u using safari on windows?

**Comment by kskenyon** [comment]
macOS 10.13.4 Beta with Safari Technology Preview.  I’m probably ahead of things.

**Comment by reloxx13** [comment]
hahaha xD

at home i got an old safari for windows (stopped development already), and bootstrap4 looks terrible in it :X

**Comment by reloxx13** [comment]
fixed, pls try again 👍 

if not, i need to check it tomorrow in a mac safari :p

**Comment by kskenyon** [comment]
You got it.  Nice work.  Thanks
