### ISSUE TITLE
List isn't working right

### ISSUE THREAD

**Issue by kskenyon** [reloxx13/SonWEB#70]
Me again...

The Start page **is** working right, however, the list page only shows the one device we tweaked to fix the uptime problem in Safari.  The others just sit there with the spinning wait symbol now. See screen shot.    I've restarted httpd, reloaded the page several times and checked all the IP addresses to be sure.  Something isn't right on the list page now.  
<img width="1440" alt="screen shot 2018-02-22 at 7 12 20 pm" src="https://user-images.githubusercontent.com/24734156/36571371-5c1d3136-1804-11e8-8824-bc3f3d3505f4.png">

Kevin

**Comment by reloxx13** [comment]
all on 5,12.0c ? strange :S

**Comment by kskenyon** [comment]
They should be on 5.12.0c.  I can’t explain this one since they work OK in the Start view and are otherwise accessible.  Weird.

K

**Comment by reloxx13** [comment]
if you access them by web interface, does they got a long loading time?

try to open teh developer console of your browser and check what it says their.

also, did you try another browser just for a test? could be another safari bug.

**Comment by reloxx13** [comment]
heya,

i increased the timeout a lil bit, pls update

**Comment by reloxx13** [comment]
nice, with this we can go on.

[Log] [LIST][updateAllStatus][8]MSG => {} (devices.js, line 159) [Error] TypeError: undefined is not an object (evaluating 'data.StatusSTS.POWER')

empty response Oo

could you check what the device with id 8 (not position, click on show more to see the id)
is answering on status 0 ?

ill make an exception handling for this case now.

**Comment by kskenyon** [comment]
{
  "StatusSTS" : {
    "Time" : "2018-02-23T15:34:06",
    "Uptime" : "0T03:52:34",
    "Vcc" : 3.013,
    "POWER" : "ON",
    "Wifi" : {
      "AP" : 1,
      "SSId" : "MOTO4C8A",
      "RSSI" : 100,
      "APMac" : "F8:CF:C5:FE:64:95"
    }
  }
}

**Comment by reloxx13** [comment]
and what device type is it? sonoff 4ch ?

ps: added error handling for this case, just update and see what your list looks like now.

**Comment by kskenyon** [comment]
D1 mini 
might be a clone
Not home to check.

**Comment by kskenyon** [comment]
No dice

[Log] /SonWEB/tmp/cache/i18n/json_i18n_en.cache.json (app.js, line 8)
[Log] [Devices][updateAllStatus]START (devices.js, line 139)
[Log] [Global][Refreshtime]10000ms (devices.js, line 38)
[Log] [Sonoff][doAjaxAll] Got response from: Status 0 (Sonoff.js, line 145)
[Log] [LIST][updateAllStatus][4]MSG => {"Status":{"Module":18,"FriendlyName":"mini1","Topic":"mini1","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":7,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://10.0.1.77:80/SonWEB/data/firmwares/sonoff-minimal.bin","Uptime":"2T06:22:42","StartupUTC":"2018-02-21T14:17:18","Sleep":0,"BootCount":80,"SaveCount":6731,"SaveAddress":"F7000"},"StatusFWR":{"Version":"5.12.0c","BuildDateTime":"2018-02-20T12:08:03","Boot":31,"Core":"2_4_0","SDK":"2.1.0(deb1901)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId1":"MOTO4C8A","SSId2":"netis_2.4G_E7D2C0","TelePeriod":300,"SetOption":"56000109"},"StatusMEM":{"ProgramSize":495,"Free":508,"Heap":19,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3},"StatusNET":{"Hostname":"mini1-7903","IPAddress":"10.0.1.117","Gateway":"10.0.1.1","Subnetmask":"255.255.255.0","DNSServer":"75.75.75.75","Mac":"5C:CF:7F:AA:BE:DF","Webserver":2,"WifiConfig":4},"StatusMQT":{"MqttHost":"10.0.1.32","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_AABEDF","MqttUser":"pi3","MAX_PACKET_SIZE":1000,"KEEPALIVE":15},"StatusTIM":{"UTC":"Fri Feb 23 20:40:00 2018","Local":"Fri Feb 23 15:40:00 2018","StartDST":"Sun Mar 04 02:00:00 2018","EndDST":"Sun Nov 04 03:00:00 2018","Timezone":99},"StatusSNS":{"Time":"2018-02-23T15:40:00","BMP280":{"Temperature":75.6,"Pressure":991},"SHT3X":{"Temperature":67.1,"Humidity":42.7},"TempUnit":"F"},"StatusSTS":{"Time":"2018-02-23T15:40:00","Uptime":"2T06:22:42","Vcc":3.002,"POWER":"ON","Wifi":{"AP":1,"SSId":"MOTO4C8A","RSSI":100,"APMac":"F8:CF:C5:FE:64:95"}}} (devices.js, line 159)
[Log] [LIST][updateAllStatus][8][ERROR] DATA => undefined (devices.js, line 170)
[Error] TypeError: undefined is not an object (evaluating 'data.ERROR')
	(anonymous function) (devices.js:183)
	each (jquery.js:370)
	each (jquery.js:137)
	(anonymous function) (devices.js:144)
	success (Sonoff.js:152)
	fire (jquery.js:3232)
	fireWith (jquery.js:3362)
	done (jquery.js:9840)
	callback (jquery.js:10311)
[Log] [Global][Refreshtime] updateStatus now (devices.js, line 40)
[Log] [Devices][updateAllStatus]SKIP (devices.js, line 214)
[Log] [Global][Refreshtime] updateStatus now (devices.js, line 40)
[Log] [Devices][updateAllStatus]SKIP (devices.js, line 214)
[Log] [Global][Refreshtime] updateStatus now (devices.js, line 40)
[Log] [Devices][updateAllStatus]SKIP (devices.js, line 214)

**Comment by kskenyon** [comment]
I think you’ve got it now.

K

**Comment by kskenyon** [comment]
Might be that a device changed IP addresses so there was a duplicate in SonWEB.  Not good.  I’m still having trouble getting my router to pass through mDNS multipath so I don’t have to use IP addresses that change.  Either that or set up fixed IP addresses for sonoffs which I don’t really want to do.
