### ISSUE TITLE
SelfUpdate Error

### ISSUE THREAD

**Issue by timota** [reloxx13/SonWEB#71]
Hi guys, 

tryed SelfUpdate and got this Warnings/Errors:

Warning: fopen(/app/sonweb/data/updates/sonoff.zip): failed to open stream: No such file or directory in /app/sonweb/includes/Selfupdate.php on line 290

Warning: curl_setopt(): supplied argument is not a valid File-Handle resource in /app/sonweb/includes/Selfupdate.php on line 303

Warning: fclose() expects parameter 1 to be resource, boolean given in /app/sonweb/includes/Selfupdate.php on line 319

Warning: filesize(): stat failed for /app/sonweb/data/updates/sonoff.zip in /app/sonweb/includes/Selfupdate.php on line 322

App running in docker: raymondmm/rpi-sonweb-alpine

**Comment by timota** [comment]
had to create updates directory inside persistent volume.

**Comment by reloxx13** [comment]
maybe @RaymondMouthaan can help :)

**Comment by RaymondMouthaan** [comment]
@timota You r right .. if the host volume doesn't exist when deploying the docker container then these kind of errors are shown. 

This could be an improvement to the docker container or maybe even better from SonWEB it's self. 
Basically there must be a check whether required files and directories exist in the data dir. If not create them, if yes use them.

@reloxx13 could this be done from SonWEB code easily?

**Comment by RaymondMouthaan** [comment]
Fixed in the latest version of the alpine docker image.
