### ISSUE TITLE
Run SonWEB as a docker container on Synology DSM

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [reloxx13/SonWEB#73]
I've been running SonWEB from a PC and love the effort, but need the PC off. I tried to run the RPI Ubuntu docker image on a Synology DSM with no success. If anyone more abled can contribute, help would be much appreciated.
I'll contribute as I can... namely translation!

**Comment by RaymondMouthaan** [comment]
Hello @MimbaMonkeyHouse,

The images (rpi-sonweb-alpine and rpi-sonweb-ubuntu) available are **only** for raspberry pi's since they are build for the arm architecture, they will not work on Synology DSM. I have myself also a Synology NAS, which has a different architecture (x86) than raspberry pi's. 
If there is enough interest I am willing to build an image for Synology as well.

**Comment by MimbaMonkeyHouse** [comment]
Hey @RaymondMouthaan,

Yea, I've actually tried to run these images on my Synology and it obviously did not work. 
I'd really love a Syno compatible image. Such an image would work with any x86 platform and would definitely add value to SonWEB. 
At the moment, it's a bit of a pain to have a PC running when I need to use this... I'd love to use this in a Syno docker as I could stop the docker image when not used directly from Home Assistant (via Dockermon) and start it when updates need to be made! Unfortunately, my skills are not there (yet!) to make one myself!

**Comment by RaymondMouthaan** [comment]
@MimbaMonkeyHouse i'll dig into building an image for x86_64 as soon as I can and inform you about is a soon its ready.

**Comment by RaymondMouthaan** [comment]
@MimbaMonkeyHouse After spending some ours of research how to build multi architecture docker images ... I've found a solution that works :)

### Install sonweb on a synology nas running docker

- Login to DSM
- Go To Docker -> Image (for unknown reason it doesn't find the image using the registry)
- Click Add -> Add from Url
- Copy / Past this url : **https://hub.docker.com/r/raymondmm/sonweb/**
- Leave all other field blank
- Click Add

![screen shot 2018-03-01 at 21 19 59](https://user-images.githubusercontent.com/25717738/36867748-61efdd4c-1d96-11e8-971f-c90a09c0336f.png)

- Choose Tag: **latest** and Click Select

![screen shot 2018-03-01 at 21 20 17](https://user-images.githubusercontent.com/25717738/36867932-109fa296-1d97-11e8-9304-5c6315f65b0b.png)

After a couple of seconds it downloads the image and you are ready to deploy a SonWEB Container.
- Make sure you create a host directory which you link to the container to persist your SonWEB data (/host/data:/data) 

Let me know if it works for you!

**Comment by MimbaMonkeyHouse** [comment]
I shall try this straight away and comment here

**Comment by MimbaMonkeyHouse** [comment]
Good news: we can now access the image via the registry.
Bad news: the container crashes on both my machine. Defined the host directory as advised. Tried to run as both host and bridge... No luck!
Here is the log:

date | stream | content
-- | -- | --
2018-03-02 08:02:28 | stdout | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
2018-03-02 08:02:28 | stdout | Starting apache...
2018-03-02 08:02:28 | stdout | Clearing any old processes...
2018-03-02 08:02:28 | stdout | NOTICE: Change 'ServerName' globally and hide server message by setting environment variable >> 'SERVER_NAME=your.server.name' in docker command or docker-compose file
2018-03-02 08:01:04 | stdout | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
2018-03-02 08:01:03 | stdout | Starting apache...
2018-03-02 08:01:03 | stdout | Clearing any old processes...
2018-03-02 08:01:03 | stdout | NOTICE: Change 'ServerName' globally and hide server message by setting environment variable >> 'SERVER_NAME=your.server.name' in docker command or docker-compose file

Not sure what's not right. What port is this set to/accessible from? Maybe, I've got a clash as few servers are running (Home Assistant, Grafana, Influxdb, Plex, Dockermon, etc)...

**Comment by RaymondMouthaan** [comment]
Yes, I saw too this morning that looking up using the registry works :-)

Above doesn't show any signs of crashing. AH00558 is just warning but can be avoided if you add an environment variable APACHE_SERVER_NAME=mysonweb.mydomain , but without it it should work. Have you tried accessing SonWeb using http://<ip_of_your_nas>:<exposed_port> ?

**Comment by MimbaMonkeyHouse** [comment]
Beh, I got it working... Sorry about the stress! Am now logging in.
Thanks so much for this. Owe you a beer or let me know if I can help!

**Comment by RaymondMouthaan** [comment]
Some more screenshots ...

![screen shot 2018-03-02 at 09 22 06](https://user-images.githubusercontent.com/25717738/36889762-acbb1912-1dfb-11e8-8cb8-a36db5e826a6.png)
![screen shot 2018-03-02 at 09 22 23](https://user-images.githubusercontent.com/25717738/36889766-afb07900-1dfb-11e8-80a8-aa7e37f13bb8.png)
![screen shot 2018-03-02 at 09 22 49](https://user-images.githubusercontent.com/25717738/36889768-b2bd9b82-1dfb-11e8-9079-881e3b81daa2.png)
![screen shot 2018-03-02 at 09 23 35](https://user-images.githubusercontent.com/25717738/36889769-b4f11dfc-1dfb-11e8-884b-844698aa8af3.png)
![screen shot 2018-03-02 at 09 24 24](https://user-images.githubusercontent.com/25717738/36889773-b8bc76ca-1dfb-11e8-813b-26e5587b9e58.png)

**Comment by MimbaMonkeyHouse** [comment]
Yup, works great. Just used self-update and played around with some setings of my many Sonoffs... Autoscan almost detected all my devices. Now I'll check the French translation: sure I'll find some issues!

**Comment by RaymondMouthaan** [comment]
Great the hear you have it working 💯 . I guess this issue can be closed now :-)

**Comment by MimbaMonkeyHouse** [comment]
Yup, all is good

**Comment by ascillato** [comment]
:+1:
