### ISSUE TITLE
Easy way to change devices positions in the list

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [reloxx13/SonWEB#77]
I believe an easy way to position each device, or, even better, the ability to group devices would really add a plus. Right now, one has to go to each device's settings to change each position.

**Comment by reloxx13** [comment]
Heya,

double click the position field in the list ;)

works also for other fields.

**Comment by MimbaMonkeyHouse** [comment]
OK, I can see I can change the POS entry. Now changing it and pressing enter then refresh reverts back to the original position. How do you save that position? Does taking the position of a higher device move all the devices down the position list?

**Comment by MimbaMonkeyHouse** [comment]
Guess I was using a bad browser... Works in Chrome, thanks!

**Comment by reloxx13** [comment]
Oo okay, which browser did u use?

**Comment by MimbaMonkeyHouse** [comment]
Stupid Safari on bloody Mac. Can you feel the love?
