### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [reloxx13/SonWEB#80]
I've been really enjoying SonWeb as it makes life a lot easier with a lot of Sonoff devices. Unfortunately, since yesterday, I am getting this error:
Parse error: syntax error, unexpected ')', expecting end of file in /app/sonweb/includes/Config.php(58) : eval()'d code on line 6
SonWeb is running as a Docker container on a Synology NAS. Anyone else have this issue? What's a quick way to fix it?

**Comment by reloxx13** [comment]
Seems like sth destoyed your MyConfig.php in the data dir.

Im not familiar with those docker images, so i cannot say what caused this.

You could either open the file with a text editor and fix the syntax if you can, its php.

Or delete ist and SonWEB should create a new one, but you will loose your settings.

Your devices are saved in another file and should be fine.
I suggest you just make a backup of the device file so if it gets corrupt, you wont loose your device list.

**Comment by MimbaMonkeyHouse** [comment]
Cheers for this @reloxx13. The deletion worked. I'll now redo the config and save it
