### ISSUE TITLE
Runtime sonoff basic different displayed & No Temp and Humidity displayed for SHT30

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/SonWEB#83]
Hai @reloxx13 ,

Runtime of a sonoff basic is different displayed in sonweb then of other devices. See the different representation in the screenshot below.

Another thing is that the temperature and humidity are not displayed for wemos + sht30, this probably because of the changes Theo made to support two i2c devices. The json object which holds the temperature and humidity has been changed. See second screenshot for an example. Basically the object key has changed to  <sensor.type>-<sensor.address>, for details see Sonoff-Tasmota/sonoff/xsns_14_sht3x.ino. 

Example of STATUS 10
```
STATUS10 = {"StatusSNS":{"Time":"2018-03-21T12:13:29","SHT3X-0x45":{"Temperature":23.6,"Humidity":44.4},"TempUnit":"C"}}
```

![screen shot 2018-03-21 at 11 48 52](https://user-images.githubusercontent.com/25717738/37706064-6f8a8534-2cfe-11e8-905c-b3ec82647225.png)

![screen shot 2018-03-21 at 12 02 50](https://user-images.githubusercontent.com/25717738/37706496-008cfdc2-2d00-11e8-8d68-13e1a05aa4a8.png)

**Comment by reloxx13** [comment]
heya,

thank for the report 👍 

2 is fixed.

coud you give me a status 0 from your sonoff basic with wrong time?
i suspect the flashing failed and its not sending the new new startup datetime in json :S
it should be in StatusPRM StartupDateTimeUtc OR StartupUTC

**Comment by RaymondMouthaan** [comment]
Great! I just check no. 2 and it looks good now 👍 

You are right, there is something wrong with the time/date on my sonoff-1 

```
15:23:10 MQT: stat/sonoff-1/STATUS = {"Status":{"Module":1,"FriendlyName":"Bed Light","Topic":"sonoff-1","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
15:23:10 MQT: stat/sonoff-1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://jakarta.indonesia/tasmota/bin/sonoff_latest-minimal.bin","RestartReason":"Software/System restart","Uptime":"0T15:23:02","StartupUTC":"","Sleep":0,"BootCount":21,"SaveCount":98,"SaveAddress":"3F8000"}}
15:23:10 MQT: stat/sonoff-1/STATUS2 = {"StatusFWR":{"Version":"5.12.0h","BuildDateTime":"2018-03-20T18:57:36","Boot":31,"Core":"2_4_0","SDK":"2.1.0(deb1901)"}}
15:23:10 MQT: stat/sonoff-1/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId1":"indonesia23","SSId2":"","TelePeriod":30,"SetOption":"00000009"}}
15:23:10 MQT: stat/sonoff-1/STATUS4 = {"StatusMEM":{"ProgramSize":503,"Free":2568,"Heap":19,"ProgramFlashSize":4096,"FlashSize":4096,"FlashMode":3}}
15:23:10 MQT: stat/sonoff-1/STATUS5 = {"StatusNET":{"Hostname":"sonoff-1-2034","IPAddress":"192.168.2.201","Gateway":"192.168.2.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.10","Mac":"68:C6:3A:A2:67:F2","Webserver":2,"WifiConfig":3}}
15:23:10 MQT: stat/sonoff-1/STATUS6 = {"StatusMQT":{"MqttHost":"mqtt.indonesia","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_A267F2","MqttUser":"DVES_USER","MqttType":2,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
15:23:10 MQT: stat/sonoff-1/STATUS7 = {"StatusTIM":{"UTC":"Thu Jan 01 15:23:10 1970","Local":"Thu Jan 01 15:23:10 1970","StartDST":"Thu Jan 01 00:00:00 1970","EndDST":"Thu Jan 01 00:00:00 1970","Timezone":1}}
15:23:10 MQT: stat/sonoff-1/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T15:23:10"}}
15:23:10 MQT: stat/sonoff-1/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T15:23:10","Uptime":"0T15:23:02","Vcc":3.400,"POWER":"OFF","Wifi":{"AP":1,"SSId":"indonesia23","RSSI":82,"APMac":"30:D3:2D:70:05:4D"}}}
```

**Comment by reloxx13** [comment]
some things you can try:

- just try to restart once
- check the NTP Server (address correct? ping or visit it with the browser)
- just try a reflash over the web ui of tasmota with minimal->normal

NtpServer\<x\> |   |  Show NTP server 1 to 3 name or ip address
-- | -- | --
NtpServerr\<x\> | 0 | Set NTP server 1 to 3 name to none and restart
NtpServerr\<x\> | 1 | Reset NTP server 1 to 3 name to user_config.h (NTP_SERVERx) and restart
NtpServerr\<x\> | <ntphost> | Set NTP server 1 to 3 name or ip address (32 chars max)

**Comment by RaymondMouthaan** [comment]
Thanks for the instructions! .. unfortunately I tried all that and did not help .. 

Finally, I enabled a local ntp server and used that in the Tasmota configuration and that helped. Time in the sonoff is perfectly synced (again). 

This also showed the correct time in Sonweb (TasmoWeb ;) ), so i close this issue now.
 
Greetz!
