### ISSUE TITLE
Can you add Ultraschall Sensor sr04 in Sonweb ?

### ISSUE THREAD

**Issue by eeprom23** [reloxx13/SonWEB#89]
Here are the Status file ! Thanks for your work !

{"StatusSNS":{"Time":"2018-04-21T16:54:56","DHT11":{"Temperature":22.0,"Humidity":55.0},"BMP280":{"Temperature":24.0,"Pressure":984.8},"SR04":{"Distance":108},"TempUnit":"C"}}

**Comment by reloxx13** [comment]
Heya,

which unit is the distance? meter? cm? or something else?

**Comment by eeprom23** [comment]
Unit is cm !

**Comment by reloxx13** [comment]
thx, im on it :)

**Comment by eeprom23** [comment]
Thx for your work !

**Comment by reloxx13** [comment]
done 👍  :)
