### ISSUE TITLE
Devices with 3 measurements overlap in Start view.  See mini1 for example.

### ISSUE THREAD

**Issue by kskenyon** [reloxx13/SonWEB#90]
<img width="1440" alt="screen shot 2018-04-24 at 9 57 22 am" src="https://user-images.githubusercontent.com/24734156/39191959-0f720b00-47a6-11e8-9188-1d9cb0315c9d.png">

**Comment by reloxx13** [comment]
Heya,

i made this on purpose, but sure i can add a lil bit margin

**Comment by reloxx13** [comment]
fixed, pls try :)

could need some arrangement depending on display resoution.
