### ISSUE TITLE
Sonweb show only 2 ds18b20 Sensor !

### ISSUE THREAD

**Issue by eeprom23** [reloxx13/SonWEB#94]
Can you please add 5 Sensor to Sonweb ?

{"StatusSNS":{"Time":"2018-05-08T11:59:09","DS18x20":{"DS1":{"Type":"DS18B20","Address":"286164123245F2E6","Temperature":18.7},"DS2":{"Type":"DS18B20","Address":"2861641233D6F406","Temperature":19.3},"DS3":{"Type":"DS18B20","Address":"286164123393BCE6","Temperature":19.4},"DS4":{"Type":"DS18B20","Address":"2861641233A768C6","Temperature":18.7}},"TempUnit":"C"}}

Sensor 5 is Not in the Status file but the Name is DS5.....

Thanks for your work !

**Comment by reloxx13** [comment]
done 👍

**Comment by eeprom23** [comment]
Thx
