### ISSUE TITLE
BME680 values not displayed

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/SonWEB#98]
Hai @reloxx13 ,

Currently the BME680 sensor values are not displayed in SonWeb.

![screen shot 2018-05-17 at 09 05 50](https://user-images.githubusercontent.com/25717738/40161582-8b7a753a-59b1-11e8-94b2-862c65ebe823.png)
![screen shot 2018-05-17 at 09 05 24](https://user-images.githubusercontent.com/25717738/40161589-903458a2-59b1-11e8-9da4-35314b9cf1ae.png)

The status 10 looks like this:
```
stat/wemos-3/STATUS10 = {"StatusSNS":{"Time":"2018-05-17T09:01:37","BME680":{"Temperature":26.9,"Humidity":37.0,"Pressure":1023.2,"Gas":144.77},"TempUnit":"C"}}
```

I guess somewhere it got broken.

Can you please fix it?

Thanks,
Ray

**Comment by reloxx13** [comment]
Every sensor got another name, so i need to add it. Also Gas is new :)

**Comment by RaymondMouthaan** [comment]
Just added it to the Tasmota Wiki [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos-D1-Mini), but to answer you question directly ;)

![wemos-bme680-main-marked](https://user-images.githubusercontent.com/25717738/40162873-84b256ba-59b5-11e8-914c-fd206000f798.jpg)

**Comment by RaymondMouthaan** [comment]
Thanks for the update! In Device List the values are displayed perfectly, however the bulb doesn't ..

![screen shot 2018-05-17 at 19 05 20](https://user-images.githubusercontent.com/25717738/40192663-547aaa1a-5a05-11e8-8182-51204ade370e.png)
